In [1]:
import numpy as np
import matplotlib.pyplot as plt
import open3d as o3d
import cv2

Jupyter environment detected. Enabling Open3D WebVisualizer.
[Open3D INFO] WebRTC GUI backend enabled.
[Open3D INFO] WebRTCWindowSystem: HTTP handshake server disabled.


In [2]:
# Open our point cloud in open3d
print("Load a ply point cloud, print it, and render it")
pcd = o3d.io.read_point_cloud("./box2_clean.ply")
print(pcd)
print(np.asarray(pcd.points))
o3d.visualization.draw_geometries([pcd])

Load a ply point cloud, print it, and render it
PointCloud with 2267839 points.
[[-0.07862443 -0.09475924 -0.95258617]
 [-0.07841891 -0.09456891 -0.95460749]
 [-0.07883772 -0.0944346  -0.95231569]
 ...
 [-0.60300362  0.45464575  0.41997862]
 [-0.35005522  0.40758854  0.52561784]
 [-0.60563791  0.93964434 -0.01528907]]


In [12]:
# Voxel downsampling
# .05 eliminates too many points
print("Downsample the point cloud with a voxel of 0.01")
downpcd = pcd.voxel_down_sample(voxel_size=0.01)
o3d.visualization.draw_geometries([downpcd])

Downsample the point cloud with a voxel of 0.05


In [4]:
# DBSCAN clustering
with o3d.utility.VerbosityContextManager(
        o3d.utility.VerbosityLevel.Debug) as cm:
    labels = np.array(
        pcd.cluster_dbscan(eps=0.04, min_points=10, print_progress=True))

max_label = labels.max()
print(f"point cloud has {max_label + 1} clusters")
colors = plt.get_cmap("tab20")(labels / (max_label if max_label > 0 else 1))
colors[labels < 0] = 0
pcd.colors = o3d.utility.Vector3dVector(colors[:, :3])
o3d.visualization.draw_geometries([pcd])